apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: Builds and runs the Internal Developer Platform
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-payments
  description: Owns checkout, payments and billing
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jon
spec:
  memberOf: [platform-team]
